//! gRPC Service Implementation for Memory Cell

use tonic::{Request, Response, Status};

// Generated protobuf modules (would be generated by tonic-build)
pub mod proto {
    pub mod cell_common {
        tonic::include_proto!("cell_common");
    }
    pub mod memory_cell {
        tonic::include_proto!("memory_cell");
    }
}

use proto::memory_cell::{
    memory_cell_service_server::MemoryCellService,
    AllocateRequest, AllocateResponse, AllocationFlags as ProtoAllocationFlags,
    AllocationInfo, CreatePoolRequest, DeallocateRequest, DefragmentRequest,
    DiagnosticsResult as ProtoDiagnosticsResult, DiagnosticIssue as ProtoDiagnosticIssue,
    GetAllocationRequest, MemoryPool as ProtoMemoryPool, MemoryStats as ProtoMemoryStats,
    PoolStats as ProtoPoolStats, PoolType as ProtoPoolType,
};
use proto::cell_common::{CellStatus, CommandResponse, Empty, HealthStatus, Heartbeat, Metrics};

use crate::{CellState, HealthStatus as CellHealthStatus, MemoryCell};

/// gRPC Memory Cell Service
pub struct MemoryCellGrpcService {
    cell: std::sync::Arc<MemoryCell>,
}

impl MemoryCellGrpcService {
    /// Create a new gRPC service
    pub fn new(cell: std::sync::Arc<MemoryCell>) -> Self {
        Self { cell }
    }
}

#[tonic::async_trait]
impl MemoryCellService for MemoryCellGrpcService {
    async fn allocate(
        &self,
        request: Request<AllocateRequest>,
    ) -> Result<Response<AllocateResponse>, Status> {
        let req = request.into_inner();

        let flags = crate::memory::AllocationFlags {
            zero_init: req.flags.as_ref().map(|f| f.zero_init).unwrap_or(false),
            executable: req.flags.as_ref().map(|f| f.executable).unwrap_or(false),
            shared: req.flags.as_ref().map(|f| f.shared).unwrap_or(false),
            huge_pages: req.flags.as_ref().map(|f| f.huge_pages).unwrap_or(false),
            pinned: req.flags.as_ref().map(|f| f.pinned).unwrap_or(false),
        };

        match self.cell.allocate(req.size, &req.pool_name, flags).await {
            Ok(allocation) => Ok(Response::new(AllocateResponse {
                success: true,
                address: allocation.address,
                actual_size: allocation.size,
                allocation_id: allocation.id,
                error_message: String::new(),
            })),
            Err(e) => Ok(Response::new(AllocateResponse {
                success: false,
                address: 0,
                actual_size: 0,
                allocation_id: String::new(),
                error_message: e.to_string(),
            })),
        }
    }

    async fn deallocate(
        &self,
        request: Request<DeallocateRequest>,
    ) -> Result<Response<CommandResponse>, Status> {
        let req = request.into_inner();

        match self.cell.deallocate(&req.allocation_id).await {
            Ok(()) => Ok(Response::new(CommandResponse {
                success: true,
                message: format!("Deallocated {}", req.allocation_id),
                error_code: 0,
                metadata: std::collections::HashMap::new(),
            })),
            Err(e) => Ok(Response::new(CommandResponse {
                success: false,
                message: e.to_string(),
                error_code: 1,
                metadata: std::collections::HashMap::new(),
            })),
        }
    }

    async fn create_pool(
        &self,
        _request: Request<CreatePoolRequest>,
    ) -> Result<Response<CommandResponse>, Status> {
        // Pool creation would be implemented here
        Ok(Response::new(CommandResponse {
            success: true,
            message: "Pool created".to_string(),
            error_code: 0,
            metadata: std::collections::HashMap::new(),
        }))
    }

    async fn destroy_pool(
        &self,
        _request: Request<Empty>,
    ) -> Result<Response<CommandResponse>, Status> {
        Ok(Response::new(CommandResponse {
            success: true,
            message: "Pool destroyed".to_string(),
            error_code: 0,
            metadata: std::collections::HashMap::new(),
        }))
    }

    async fn get_stats(&self, _request: Request<Empty>) -> Result<Response<ProtoMemoryStats>, Status> {
        let stats = self.cell.get_stats().await;

        Ok(Response::new(ProtoMemoryStats {
            total_memory: stats.total_memory,
            used_memory: stats.used_memory,
            available_memory: stats.available_memory,
            cached_memory: stats.cached_memory,
            shared_memory: stats.shared_memory,
            utilization_percent: stats.utilization_percent,
            allocation_count: stats.allocation_count,
            pool_count: stats.pool_count,
            pools: stats.pools.into_iter().map(|p| ProtoPoolStats {
                name: p.name,
                total_size: p.total_size,
                used_size: p.used_size,
                allocation_count: p.allocation_count,
                fragmentation_percent: p.fragmentation_percent,
            }).collect(),
        }))
    }

    async fn get_allocation(
        &self,
        _request: Request<GetAllocationRequest>,
    ) -> Result<Response<AllocationInfo>, Status> {
        Err(Status::unimplemented("Not implemented"))
    }

    type ListPoolsStream = std::pin::Pin<
        Box<dyn futures::Stream<Item = Result<ProtoMemoryPool, Status>> + Send>,
    >;

    async fn list_pools(
        &self,
        _request: Request<Empty>,
    ) -> Result<Response<Self::ListPoolsStream>, Status> {
        Err(Status::unimplemented("Not implemented"))
    }

    async fn defragment(
        &self,
        _request: Request<DefragmentRequest>,
    ) -> Result<Response<CommandResponse>, Status> {
        Ok(Response::new(CommandResponse {
            success: true,
            message: "Defragmentation completed".to_string(),
            error_code: 0,
            metadata: std::collections::HashMap::new(),
        }))
    }

    async fn run_diagnostics(
        &self,
        _request: Request<Empty>,
    ) -> Result<Response<ProtoDiagnosticsResult>, Status> {
        let result = self.cell.run_diagnostics().await;

        Ok(Response::new(ProtoDiagnosticsResult {
            healthy: result.healthy,
            issues: result.issues.into_iter().map(|i| ProtoDiagnosticIssue {
                severity: format!("{}", i.severity),
                component: i.component,
                description: i.description,
                suggested_action: i.suggested_action,
            }).collect(),
            recommendations: result.recommendations,
        }))
    }

    async fn get_heartbeat(&self, _request: Request<Empty>) -> Result<Response<Heartbeat>, Status> {
        let state = self.cell.state().await;
        let health = self.cell.health().await;

        Ok(Response::new(Heartbeat {
            cell_id: self.cell.id().to_string(),
            timestamp: std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_millis() as i64,
            status: match state {
                CellState::Initializing => CellStatus::Initializing,
                CellState::Active => CellStatus::Active,
                CellState::Degraded => CellStatus::Degraded,
                CellState::Healing => CellStatus::Healing,
                CellState::Shutdown => CellStatus::Shutdown,
            },
            health: match health {
                CellHealthStatus::Healthy => HealthStatus::Healthy,
                CellHealthStatus::Warning => HealthStatus::Warning,
                CellHealthStatus::Critical => HealthStatus::Critical,
            },
        }))
    }

    async fn get_metrics(&self, _request: Request<Empty>) -> Result<Response<Metrics>, Status> {
        let stats = self.cell.get_stats().await;
        let state = self.cell.state().await;
        let health = self.cell.health().await;

        let mut gauge_metrics = std::collections::HashMap::new();
        gauge_metrics.insert("total_memory".to_string(), stats.total_memory as f64);
        gauge_metrics.insert("used_memory".to_string(), stats.used_memory as f64);
        gauge_metrics.insert("utilization".to_string(), stats.utilization_percent);

        let mut counter_metrics = std::collections::HashMap::new();
        counter_metrics.insert("allocation_count".to_string(), stats.allocation_count as i64);

        Ok(Response::new(Metrics {
            cell_id: self.cell.id().to_string(),
            cell_type: "memory".to_string(),
            timestamp: std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_millis() as i64,
            gauge_metrics,
            counter_metrics,
            status: match state {
                CellState::Initializing => CellStatus::Initializing,
                CellState::Active => CellStatus::Active,
                CellState::Degraded => CellStatus::Degraded,
                CellState::Healing => CellStatus::Healing,
                CellState::Shutdown => CellStatus::Shutdown,
            },
            health: match health {
                CellHealthStatus::Healthy => HealthStatus::Healthy,
                CellHealthStatus::Warning => HealthStatus::Warning,
                CellHealthStatus::Critical => HealthStatus::Critical,
            },
        }))
    }
}
