//! Code Generation for Koli Language
//!
//! This module generates target code from the typed AST.
//! Currently supports Rust code generation for integration with KolibriOS.

use alloc::string::String;
use alloc::vec::Vec;

use super::ast::*;
use super::type_check::{TypedProgram, TypedItem, TypedStatement, TypedExpression, TypedExprKind};
use super::{CompileOptions, CompileOutput, CompileError, Target};

/// Generate code from typed AST
pub fn generate(program: &TypedProgram, options: &CompileOptions) -> Result<CompileOutput, CompileError> {
    match options.target {
        Target::Native | Target::LLVM => generate_rust(program, options),
        Target::Wasm => generate_wasm(program, options),
        Target::Bytecode => generate_bytecode(program, options),
    }
}

/// Generate Rust code
fn generate_rust(program: &TypedProgram, options: &CompileOptions) -> Result<CompileOutput, CompileError> {
    let mut generator = RustCodeGenerator::new(options.clone());
    generator.generate(program)
}

/// Generate WebAssembly
fn generate_wasm(program: &TypedProgram, options: &CompileOptions) -> Result<CompileOutput, CompileError> {
    // For now, generate Rust and rely on wasm32 target compilation
    let mut generator = RustCodeGenerator::new(options.clone());
    generator.generate(program)
}

/// Generate bytecode for Koli VM
fn generate_bytecode(program: &TypedProgram, _options: &CompileOptions) -> Result<CompileOutput, CompileError> {
    let mut generator = BytecodeGenerator::new();
    generator.generate(program)
}

/// Rust code generator
struct RustCodeGenerator {
    options: CompileOptions,
    output: String,
    indent: usize,
    #[allow(dead_code)]
    imports: Vec<String>,
}

impl RustCodeGenerator {
    fn new(options: CompileOptions) -> Self {
        Self {
            options,
            output: String::new(),
            indent: 0,
            imports: Vec::new(),
        }
    }

    fn generate(&mut self, program: &TypedProgram) -> Result<CompileOutput, CompileError> {
        // Add standard header
        self.emit("// Generated by Koli Compiler");
        self.emit("// KolibriOS AI - Auto-generated Rust code");
        self.emit("");
        self.emit("#![allow(unused)]");
        self.emit("");

        // Add imports
        self.emit("use std::collections::HashMap;");
        self.emit("use kolibri_cells::*;");
        self.emit("use kolibri_kernel::*;");
        self.emit("");

        // Generate each item
        for item in &program.items {
            self.generate_item(item)?;
        }

        // Add main function if debug build
        if self.options.debug_info {
            self.emit("");
            self.emit("fn main() {");
            self.indent += 1;
            self.emit("println!(\"Koli program compiled successfully\");");
            self.indent -= 1;
            self.emit("}");
        }

        let code = self.output.clone().into_bytes();

        Ok(CompileOutput {
            code,
            symbols: Vec::new(),
            warnings: Vec::new(),
            debug_info: None,
        })
    }

    fn generate_item(&mut self, item: &TypedItem) -> Result<(), CompileError> {
        match item {
            TypedItem::Function(func) => self.generate_function(func),
            TypedItem::Ai(ai) => self.generate_ai_definition(ai),
            TypedItem::Cell(cell) => self.generate_cell_definition(cell),
        }
    }

    fn generate_function(&mut self, func: &super::type_check::TypedFunction) -> Result<(), CompileError> {
        // Function signature
        let params: String = func.params
            .iter()
            .map(|p| format!("{}: {}", p.name, self.type_to_rust(&p.ty)))
            .collect::<Vec<_>>()
            .join(", ");

        let return_type = if func.return_type == Type::Void {
            String::new()
        } else {
            format!(" -> {}", self.type_to_rust(&func.return_type))
        };

        self.emit(&format!("pub fn {}({}){} {{", func.name, params, return_type));
        self.indent += 1;

        // Function body
        self.generate_block(&func.body)?;

        self.indent -= 1;
        self.emit("}");
        self.emit("");

        Ok(())
    }

    fn generate_ai_definition(&mut self, ai: &super::type_check::TypedAiDefinition) -> Result<(), CompileError> {
        // Generate AI struct
        self.emit(&format!("pub struct {} {{", ai.name));
        self.indent += 1;
        self.emit("model: String,");
        self.emit("context: Vec<String>,");
        for cap in &ai.capabilities {
            self.emit(&format!("{}_capability: bool,", cap.name));
        }
        self.indent -= 1;
        self.emit("}");
        self.emit("");

        // Generate AI implementation
        self.emit(&format!("impl {} {{", ai.name));
        self.indent += 1;

        // Constructor
        self.emit(&format!("pub fn new() -> Self {{"));
        self.indent += 1;
        self.emit(&format!("Self {{"));
        self.indent += 1;
        self.emit("model: String::from(\"default\"),");
        self.emit("context: Vec::new(),");
        for cap in &ai.capabilities {
            self.emit(&format!("{}_capability: true,", cap.name));
        }
        self.indent -= 1;
        self.emit("}");
        self.indent -= 1;
        self.emit("}");
        self.emit("");

        // Ask method
        self.emit("pub fn ask(&self, prompt: &str) -> String {");
        self.indent += 1;
        self.emit("// AI inference call - integrate with KolibriOS AI bridge");
        self.emit("ai_bridge::infer(&self.model, prompt)");
        self.indent -= 1;
        self.emit("}");

        self.indent -= 1;
        self.emit("}");
        self.emit("");

        Ok(())
    }

    fn generate_cell_definition(&mut self, cell: &super::type_check::TypedCellDefinition) -> Result<(), CompileError> {
        // Generate Cell struct
        self.emit(&format!("pub struct {} {{", cell.name));
        self.indent += 1;

        for prop in &cell.properties {
            self.emit(&format!("{}: {},", prop.name, self.type_to_rust(&prop.ty)));
        }

        // Add cell state
        self.emit("state: CellState,");
        self.emit("metrics: CellMetrics,");

        self.indent -= 1;
        self.emit("}");
        self.emit("");

        // Generate Cell implementation
        self.emit(&format!("impl {}Cell for {} {{", cell.name, cell.name));
        self.indent += 1;

        // Cell trait methods
        self.emit("fn state(&self) -> &CellState { &self.state }");
        self.emit("fn metrics(&self) -> &CellMetrics { &self.metrics }");
        self.emit("fn heal(&mut self) { /* Self-healing logic */ }");

        self.indent -= 1;
        self.emit("}");
        self.emit("");

        // Generate behavior implementations
        self.emit(&format!("impl {} {{", cell.name));
        self.indent += 1;

        // Constructor
        self.emit(&format!("pub fn new() -> Self {{"));
        self.indent += 1;
        self.emit(&format!("Self {{"));
        self.indent += 1;
        for prop in &cell.properties {
            if let Some(default) = &prop.default_value {
                let val = self.expression_to_rust_value(default);
                self.emit(&format!("{}: {},", prop.name, val));
            } else {
                self.emit(&format!("{}: Default::default(),", prop.name));
            }
        }
        self.emit("state: CellState::Healthy,");
        self.emit("metrics: CellMetrics::default(),");
        self.indent -= 1;
        self.emit("}");
        self.indent -= 1;
        self.emit("}");
        self.emit("");

        // Generate each behavior
        for behavior in &cell.behaviors {
            self.generate_behavior(behavior)?;
        }

        self.indent -= 1;
        self.emit("}");
        self.emit("");

        Ok(())
    }

    fn generate_behavior(&mut self, behavior: &super::type_check::TypedBehavior) -> Result<(), CompileError> {
        let params: String = behavior.params
            .iter()
            .map(|p| format!("{}: {}", p.name, self.type_to_rust(&p.ty)))
            .collect::<Vec<_>>()
            .join(", ");

        let return_type = if behavior.return_type == Type::Void {
            String::new()
        } else {
            format!(" -> {}", self.type_to_rust(&behavior.return_type))
        };

        self.emit(&format!("pub fn {}({}){} {{", behavior.name, params, return_type));
        self.indent += 1;

        self.generate_block(&behavior.body)?;

        self.indent -= 1;
        self.emit("}");
        self.emit("");

        Ok(())
    }

    fn generate_block(&mut self, block: &super::type_check::TypedBlock) -> Result<(), CompileError> {
        for stmt in &block.statements {
            self.generate_statement(stmt)?;
        }
        Ok(())
    }

    fn generate_statement(&mut self, stmt: &TypedStatement) -> Result<(), CompileError> {
        match stmt {
            TypedStatement::Let { name, ty, value } => {
                let rust_ty = self.type_to_rust(ty);
                let rust_val = self.expression_to_rust(value);
                self.emit(&format!("let {}: {} = {};", name, rust_ty, rust_val));
            }
            TypedStatement::Return(expr) => {
                match expr {
                    Some(e) => {
                        let rust_val = self.expression_to_rust(e);
                        self.emit(&format!("return {};", rust_val));
                    }
                    None => {
                        self.emit("return;");
                    }
                }
            }
            TypedStatement::If { condition, then_block, else_block } => {
                let cond = self.expression_to_rust(condition);
                self.emit(&format!("if {} {{", cond));
                self.indent += 1;
                self.generate_block(then_block)?;
                self.indent -= 1;

                if let Some(else_b) = else_block {
                    self.emit("} else {");
                    self.indent += 1;
                    self.generate_block(else_b)?;
                    self.indent -= 1;
                }
                self.emit("}");
            }
            TypedStatement::For { var, iterable, body } => {
                let iter = self.expression_to_rust(iterable);
                self.emit(&format!("for {} in {} {{", var, iter));
                self.indent += 1;
                self.generate_block(body)?;
                self.indent -= 1;
                self.emit("}");
            }
            TypedStatement::Ask(expr) => {
                let prompt = self.expression_to_rust(expr);
                self.emit(&format!("ai_bridge::ask({});", prompt));
            }
            TypedStatement::Expression(expr) => {
                let rust_val = self.expression_to_rust(expr);
                self.emit(&format!("{};", rust_val));
            }
            TypedStatement::Assignment { target, value } => {
                let target_str = self.expression_to_rust(target);
                let value_str = self.expression_to_rust(value);
                self.emit(&format!("{} = {};", target_str, value_str));
            }
        }
        Ok(())
    }

    fn expression_to_rust(&self, expr: &TypedExpression) -> String {
        match &expr.kind {
            TypedExprKind::Literal(lit) => self.literal_to_rust(lit),
            TypedExprKind::Identifier(name) => name.clone(),
            TypedExprKind::Binary { left, op, right } => {
                let left_str = self.expression_to_rust(left);
                let right_str = self.expression_to_rust(right);
                let op_str = self.binary_op_to_rust(*op);
                format!("({} {} {})", left_str, op_str, right_str)
            }
            TypedExprKind::Call { name, args } => {
                let args_str = args
                    .iter()
                    .map(|a| self.expression_to_rust(a))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("{}({})", name, args_str)
            }
            TypedExprKind::MethodCall { receiver, method, args } => {
                let recv_str = self.expression_to_rust(receiver);
                let args_str = args
                    .iter()
                    .map(|a| self.expression_to_rust(a))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("{}.{}({})", recv_str, method, args_str)
            }
            TypedExprKind::FieldAccess { receiver, field } => {
                let recv_str = self.expression_to_rust(receiver);
                format!("{}.{}", recv_str, field)
            }
            TypedExprKind::AiCall { model, prompt } => {
                let prompt_str = self.expression_to_rust(prompt);
                format!("{}::ask(&format!(\"{}\"))", model, prompt_str)
            }
        }
    }

    fn expression_to_rust_value(&self, expr: &TypedExpression) -> String {
        self.expression_to_rust(expr)
    }

    fn literal_to_rust(&self, lit: &Literal) -> String {
        match lit {
            Literal::Int(n) => n.to_string(),
            Literal::Float(f) => format!("{:.6}", f),
            Literal::String(s) => format!("String::from(\"{}\")", s),
            Literal::Bool(b) => b.to_string(),
        }
    }

    fn binary_op_to_rust(&self, op: BinaryOp) -> &'static str {
        match op {
            BinaryOp::Add => "+",
            BinaryOp::Sub => "-",
            BinaryOp::Mul => "*",
            BinaryOp::Div => "/",
            BinaryOp::Eq => "==",
            BinaryOp::Ne => "!=",
            BinaryOp::Lt => "<",
            BinaryOp::Le => "<=",
            BinaryOp::Gt => ">",
            BinaryOp::Ge => ">=",
            BinaryOp::And => "&&",
            BinaryOp::Or => "||",
        }
    }

    fn type_to_rust(&self, ty: &Type) -> String {
        match ty {
            Type::Int => "i64".to_string(),
            Type::Float => "f64".to_string(),
            Type::Bool => "bool".to_string(),
            Type::String => "String".to_string(),
            Type::Void => "()".to_string(),
            Type::Custom(name) => name.clone(),
        }
    }

    fn emit(&mut self, line: &str) {
        if line.is_empty() {
            self.output.push('\n');
        } else {
            for _ in 0..self.indent {
                self.output.push_str("    ");
            }
            self.output.push_str(line);
            self.output.push('\n');
        }
    }
}

/// Bytecode generator for Koli VM
struct BytecodeGenerator {
    bytecode: Vec<u8>,
    #[allow(dead_code)]
    constants: Vec<Constant>,
}

/// Bytecode constant
#[allow(dead_code)]
enum Constant {
    Int(i64),
    Float(f64),
    String(String),
}

impl BytecodeGenerator {
    fn new() -> Self {
        Self {
            bytecode: Vec::new(),
            constants: Vec::new(),
        }
    }

    fn generate(&mut self, program: &TypedProgram) -> Result<CompileOutput, CompileError> {
        // Bytecode header
        self.emit_byte(0x4B); // 'K'
        self.emit_byte(0x4F); // 'O'
        self.emit_byte(0x4C); // 'L'
        self.emit_byte(0x49); // 'I'

        // Version
        self.emit_byte(0x00);
        self.emit_byte(0x01);

        // Number of items
        self.emit_u16(program.items.len() as u16);

        // Generate bytecode for each item
        for item in &program.items {
            self.generate_item(item)?;
        }

        // Halt instruction
        self.emit_byte(OpCode::HALT as u8);

        Ok(CompileOutput {
            code: self.bytecode.clone(),
            symbols: Vec::new(),
            warnings: Vec::new(),
            debug_info: None,
        })
    }

    fn generate_item(&mut self, item: &TypedItem) -> Result<(), CompileError> {
        match item {
            TypedItem::Function(func) => self.generate_function(func),
            TypedItem::Ai(ai) => self.generate_ai(ai),
            TypedItem::Cell(cell) => self.generate_cell(cell),
        }
    }

    fn generate_function(&mut self, func: &super::type_check::TypedFunction) -> Result<(), CompileError> {
        // Function marker
        self.emit_byte(OpCode::FUNC as u8);

        // Function name length and name
        self.emit_u16(func.name.len() as u16);
        for b in func.name.bytes() {
            self.emit_byte(b);
        }

        // Number of parameters
        self.emit_byte(func.params.len() as u8);

        // Generate body
        self.generate_block(&func.body)?;

        // Return
        self.emit_byte(OpCode::RET as u8);

        Ok(())
    }

    fn generate_ai(&mut self, ai: &super::type_check::TypedAiDefinition) -> Result<(), CompileError> {
        // AI definition marker
        self.emit_byte(OpCode::AI_DEF as u8);

        // AI name
        self.emit_u16(ai.name.len() as u16);
        for b in ai.name.bytes() {
            self.emit_byte(b);
        }

        // Number of capabilities
        self.emit_byte(ai.capabilities.len() as u8);

        for cap in &ai.capabilities {
            self.emit_u16(cap.name.len() as u16);
            for b in cap.name.bytes() {
                self.emit_byte(b);
            }
        }

        Ok(())
    }

    fn generate_cell(&mut self, cell: &super::type_check::TypedCellDefinition) -> Result<(), CompileError> {
        // Cell definition marker
        self.emit_byte(OpCode::CELL_DEF as u8);

        // Cell name
        self.emit_u16(cell.name.len() as u16);
        for b in cell.name.bytes() {
            self.emit_byte(b);
        }

        // Number of behaviors
        self.emit_byte(cell.behaviors.len() as u8);

        for behavior in &cell.behaviors {
            self.generate_behavior(behavior)?;
        }

        Ok(())
    }

    fn generate_behavior(&mut self, behavior: &super::type_check::TypedBehavior) -> Result<(), CompileError> {
        // Behavior marker
        self.emit_byte(OpCode::BEHAVIOR as u8);

        // Behavior name
        self.emit_u16(behavior.name.len() as u16);
        for b in behavior.name.bytes() {
            self.emit_byte(b);
        }

        // Generate body
        self.generate_block(&behavior.body)?;

        // Return
        self.emit_byte(OpCode::RET as u8);

        Ok(())
    }

    fn generate_block(&mut self, block: &super::type_check::TypedBlock) -> Result<(), CompileError> {
        for stmt in &block.statements {
            self.generate_statement(stmt)?;
        }
        Ok(())
    }

    fn generate_statement(&mut self, stmt: &TypedStatement) -> Result<(), CompileError> {
        match stmt {
            TypedStatement::Let { name, value, .. } => {
                self.generate_expression(value)?;
                self.emit_byte(OpCode::STORE as u8);
                self.emit_u16(name.len() as u16);
                for b in name.bytes() {
                    self.emit_byte(b);
                }
            }
            TypedStatement::Return(Some(expr)) => {
                self.generate_expression(expr)?;
                self.emit_byte(OpCode::RET as u8);
            }
            TypedStatement::Return(None) => {
                self.emit_byte(OpCode::RET_VOID as u8);
            }
            TypedStatement::If { condition, then_block, else_block } => {
                self.generate_expression(condition)?;
                self.emit_byte(OpCode::JMP_IF_FALSE as u8);
                let then_start = self.bytecode.len();
                self.emit_u16(0); // Placeholder for jump offset

                self.generate_block(then_block)?;

                if let Some(else_b) = else_block {
                    self.emit_byte(OpCode::JMP as u8);
                    let else_start = self.bytecode.len();
                    self.emit_u16(0); // Placeholder

                    // Patch then jump
                    let offset = self.bytecode.len() as u16;
                    self.patch_u16(then_start, offset);

                    self.generate_block(else_b)?;

                    // Patch else jump
                    let end_offset = self.bytecode.len() as u16;
                    self.patch_u16(else_start, end_offset);
                } else {
                    // Patch then jump
                    let offset = self.bytecode.len() as u16;
                    self.patch_u16(then_start, offset);
                }
            }
            TypedStatement::For { var, iterable, body } => {
                // Push iterable
                self.generate_expression(iterable)?;
                self.emit_byte(OpCode::ITER_START as u8);

                // Loop start
                let loop_start = self.bytecode.len();

                // Check if more elements
                self.emit_byte(OpCode::ITER_HAS_NEXT as u8);
                self.emit_byte(OpCode::JMP_IF_FALSE as u8);
                let loop_end = self.bytecode.len();
                self.emit_u16(0); // Placeholder

                // Get next element and store
                self.emit_byte(OpCode::ITER_NEXT as u8);
                self.emit_byte(OpCode::STORE as u8);
                self.emit_u16(var.len() as u16);
                for b in var.bytes() {
                    self.emit_byte(b);
                }

                // Body
                self.generate_block(body)?;

                // Jump back
                self.emit_byte(OpCode::JMP as u8);
                self.emit_u16(loop_start as u16);

                // Patch end
                self.patch_u16(loop_end, self.bytecode.len() as u16);
            }
            TypedStatement::Ask(expr) => {
                self.generate_expression(expr)?;
                self.emit_byte(OpCode::AI_ASK as u8);
            }
            TypedStatement::Expression(expr) => {
                self.generate_expression(expr)?;
                self.emit_byte(OpCode::POP as u8);
            }
            TypedStatement::Assignment { target, value } => {
                self.generate_expression(value)?;
                match &target.kind {
                    TypedExprKind::Identifier(name) => {
                        self.emit_byte(OpCode::STORE as u8);
                        self.emit_u16(name.len() as u16);
                        for b in name.bytes() {
                            self.emit_byte(b);
                        }
                    }
                    TypedExprKind::FieldAccess { receiver, field } => {
                        self.generate_expression(receiver)?;
                        self.emit_byte(OpCode::SET_FIELD as u8);
                        self.emit_u16(field.len() as u16);
                        for b in field.bytes() {
                            self.emit_byte(b);
                        }
                    }
                    _ => {}
                }
            }
        }
        Ok(())
    }

    fn generate_expression(&mut self, expr: &TypedExpression) -> Result<(), CompileError> {
        match &expr.kind {
            TypedExprKind::Literal(lit) => {
                match lit {
                    Literal::Int(n) => {
                        self.emit_byte(OpCode::PUSH_INT as u8);
                        self.emit_i64(*n);
                    }
                    Literal::Float(f) => {
                        self.emit_byte(OpCode::PUSH_FLOAT as u8);
                        self.emit_f64(*f);
                    }
                    Literal::String(s) => {
                        self.emit_byte(OpCode::PUSH_STR as u8);
                        self.emit_u16(s.len() as u16);
                        for b in s.bytes() {
                            self.emit_byte(b);
                        }
                    }
                    Literal::Bool(b) => {
                        self.emit_byte(if *b { OpCode::PUSH_TRUE as u8 } else { OpCode::PUSH_FALSE as u8 });
                    }
                }
            }
            TypedExprKind::Identifier(name) => {
                self.emit_byte(OpCode::LOAD as u8);
                self.emit_u16(name.len() as u16);
                for b in name.bytes() {
                    self.emit_byte(b);
                }
            }
            TypedExprKind::Binary { left, op, right } => {
                self.generate_expression(left)?;
                self.generate_expression(right)?;
                self.emit_byte(self.binary_op_to_bytecode(*op));
            }
            TypedExprKind::Call { name, args } => {
                for arg in args {
                    self.generate_expression(arg)?;
                }
                self.emit_byte(OpCode::CALL as u8);
                self.emit_u16(name.len() as u16);
                for b in name.bytes() {
                    self.emit_byte(b);
                }
                self.emit_byte(args.len() as u8);
            }
            TypedExprKind::MethodCall { receiver, method, args } => {
                self.generate_expression(receiver)?;
                for arg in args {
                    self.generate_expression(arg)?;
                }
                self.emit_byte(OpCode::METHOD_CALL as u8);
                self.emit_u16(method.len() as u16);
                for b in method.bytes() {
                    self.emit_byte(b);
                }
                self.emit_byte(args.len() as u8);
            }
            TypedExprKind::FieldAccess { receiver, field } => {
                self.generate_expression(receiver)?;
                self.emit_byte(OpCode::GET_FIELD as u8);
                self.emit_u16(field.len() as u16);
                for b in field.bytes() {
                    self.emit_byte(b);
                }
            }
            TypedExprKind::AiCall { model, prompt } => {
                self.generate_expression(prompt)?;
                self.emit_byte(OpCode::AI_CALL as u8);
                self.emit_u16(model.len() as u16);
                for b in model.bytes() {
                    self.emit_byte(b);
                }
            }
        }
        Ok(())
    }

    fn binary_op_to_bytecode(&self, op: BinaryOp) -> u8 {
        match op {
            BinaryOp::Add => OpCode::ADD as u8,
            BinaryOp::Sub => OpCode::SUB as u8,
            BinaryOp::Mul => OpCode::MUL as u8,
            BinaryOp::Div => OpCode::DIV as u8,
            BinaryOp::Eq => OpCode::EQ as u8,
            BinaryOp::Ne => OpCode::NE as u8,
            BinaryOp::Lt => OpCode::LT as u8,
            BinaryOp::Le => OpCode::LE as u8,
            BinaryOp::Gt => OpCode::GT as u8,
            BinaryOp::Ge => OpCode::GE as u8,
            BinaryOp::And => OpCode::AND as u8,
            BinaryOp::Or => OpCode::OR as u8,
        }
    }

    fn emit_byte(&mut self, b: u8) {
        self.bytecode.push(b);
    }

    fn emit_u16(&mut self, n: u16) {
        self.bytecode.push((n >> 8) as u8);
        self.bytecode.push(n as u8);
    }

    fn emit_i64(&mut self, n: i64) {
        for b in n.to_be_bytes() {
            self.bytecode.push(b);
        }
    }

    fn emit_f64(&mut self, f: f64) {
        for b in f.to_be_bytes() {
            self.bytecode.push(b);
        }
    }

    fn patch_u16(&mut self, pos: usize, value: u16) {
        self.bytecode[pos] = (value >> 8) as u8;
        self.bytecode[pos + 1] = value as u8;
    }
}

/// Bytecode opcodes
#[repr(u8)]
enum OpCode {
    HALT = 0x00,

    // Stack operations
    PUSH_INT = 0x10,
    PUSH_FLOAT = 0x11,
    PUSH_STR = 0x12,
    PUSH_TRUE = 0x13,
    PUSH_FALSE = 0x14,
    POP = 0x15,
    DUP = 0x16,

    // Variable operations
    LOAD = 0x20,
    STORE = 0x21,

    // Arithmetic
    ADD = 0x30,
    SUB = 0x31,
    MUL = 0x32,
    DIV = 0x33,

    // Comparison
    EQ = 0x40,
    NE = 0x41,
    LT = 0x42,
    LE = 0x43,
    GT = 0x44,
    GE = 0x45,

    // Logical
    AND = 0x50,
    OR = 0x51,
    NOT = 0x52,

    // Control flow
    JMP = 0x60,
    JMP_IF_FALSE = 0x61,
    CALL = 0x62,
    RET = 0x63,
    RET_VOID = 0x64,

    // Functions
    FUNC = 0x70,

    // Object operations
    GET_FIELD = 0x80,
    SET_FIELD = 0x81,
    METHOD_CALL = 0x82,

    // Iteration
    ITER_START = 0x90,
    ITER_HAS_NEXT = 0x91,
    ITER_NEXT = 0x92,

    // AI operations
    AI_DEF = 0xA0,
    AI_ASK = 0xA1,
    AI_CALL = 0xA2,

    // Cell operations
    CELL_DEF = 0xB0,
    BEHAVIOR = 0xB1,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_rust_codegen_simple() {
        // Simple test that codegen module compiles
        let options = CompileOptions::default();
        let _generator = RustCodeGenerator::new(options);
    }
}
